FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

LABEL name="hunyuan3d21-python-base"

WORKDIR /workspace

# system deps
RUN apt-get update && apt-get install -y \
    build-essential git wget vim unzip git-lfs \
    libegl1-mesa-dev libglib2.0-0 \
    pkg-config libglvnd0 libgl1 libglx0 libegl1 libgles2 \
    libglvnd-dev libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev \
    cmake curl mesa-utils-extra libxrender1 \
    libeigen3-dev python3-dev python3-setuptools libcgal-dev \
    libxi6 libgconf-2-4 libxkbcommon-x11-0 libsm6 libxext6 libxrender-dev

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYOPENGL_PLATFORM=egl

# CUDA env
ENV CUDA_HOME=/usr/local/cuda
ENV PATH=${CUDA_HOME}/bin:${PATH}
ENV LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
ENV TORCH_CUDA_ARCH_LIST="6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0"

# install miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    chmod +x Miniconda3-latest-Linux-x86_64.sh && \
    ./Miniconda3-latest-Linux-x86_64.sh -b -p /workspace/miniconda3 && \
    rm Miniconda3-latest-Linux-x86_64.sh

ENV PATH="/workspace/miniconda3/bin:${PATH}"

RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

RUN conda create -n hunyuan3d21 python=3.10
ENV PATH="/workspace/miniconda3/envs/hunyuan3d21/bin:${PATH}"

RUN conda install -y ninja
RUN conda install -y cuda -c nvidia/label/cuda-12.4.1
RUN conda install -y -c conda-forge libstdcxx-ng

RUN pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 \
    --index-url https://download.pytorch.org/whl/cu124

# copy only requirements first (cache friendly)
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir \
    --extra-index-url https://mirrors.aliyun.com/pypi/simple \
    -r /tmp/requirements.txt
ENV LD_LIBRARY_PATH="/workspace/miniconda3/envs/hunyuan3d21/lib:${LD_LIBRARY_PATH}"
